# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='', max_length=15)),
                ('ratio', models.FloatField(default=1)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(default='unknown', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='football', max_length=20)),
                ('league', models.CharField(default='EPL', max_length=20)),
                ('team1', models.CharField(default='', max_length=20)),
                ('team2', models.CharField(default='', max_length=20)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 3, 8, 23, 41, 44, 651395))),
                ('win_ratio', models.FloatField(default=1)),
                ('draw_ratio', models.FloatField(default=1)),
                ('lose_ratio', models.FloatField(default=1)),
                ('total_value', models.FloatField(default=2.5)),
                ('over_ratio', models.FloatField(default=1)),
                ('under_ratio', models.FloatField(default=1)),
                ('total1', models.CharField(default='--', max_length=3)),
                ('total2', models.CharField(default='--', max_length=3)),
                ('max_bet', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(default='', max_length=15)),
                ('balance', models.FloatField(default=0)),
                ('qiwi', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
