# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 20, 53, 41, 405305)),
        ),
    ]
