# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170309_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='', max_length=20)),
                ('league', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='league',
            field=models.CharField(default='EPL', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='team1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='team2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 23, 36, 28, 418030)),
        ),
    ]
