# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170311_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 11, 49, 30, 516791)),
        ),
    ]
