# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170315_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='handicap1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='handicap1_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='handicap2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='handicap2_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 12, 25, 47, 498647)),
        ),
    ]
